name = "BarnesHut"
uuid = "8ee9dce3-ecb7-4a7c-a5f6-57a92b6e1c56"
authors = ["PietroDomi <pietro.dominietto@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
